services:
  coturn:
    image: coturn/coturn
    restart: always
    command: >
      turnserver -n
      --lt-cred-mech
      --realm=myapp.com
      --user=webrtcuser:webrtccred
      --no-tls --no-dtls
      --log-file=stdout
      --min-port=20000
      --max-port=20100
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349" # optional TLS
      - "20000-20100:20000-20100/udp"

  janus:
    image: canyan/janus-gateway:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8188:8188" # WebSocket
      - "8088:8088" # REST API
      - "10000-10200:10000-10200/udp" # RTP
    volumes:
      - ./janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg:ro
      - ./janus/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg:ro
