# Generated by Django 5.1.6 on 2025-08-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='page_number',
        ),
    ]
