# Generated by Django 5.1.6 on 2025-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bookdata_page_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTeachingContentForUser',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('q_and_a', models.JSONField()),
                ('user_has_learned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Book Teaching Content For Users',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='bookdata',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
