# Generated by Django 5.1.6 on 2025-08-26 16:23

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookteachingcontentforuser_bookdata_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('chunk_html', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                'verbose_name_plural': 'Book Chunks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BookForUser',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Book For Users',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BookTeachingContent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('q_and_a', models.JSONField()),
                ('user_has_learned', models.BooleanField(default=False)),
                ('book_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_contents', to='app.bookforuser')),
            ],
            options={
                'verbose_name_plural': 'Book Teaching Contents',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='BookData',
        ),
        migrations.DeleteModel(
            name='BookTeachingContentForUser',
        ),
        migrations.AddField(
            model_name='bookchunk',
            name='book_for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='app.bookforuser'),
        ),
    ]
