# Generated by Django 5.1.6 on 2025-08-26 17:32

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookchunk_bookforuser_bookteachingcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
