# Generated by Django 5.1.6 on 2025-08-26 20:53

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bookchunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChatMessage',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('sender', models.CharField(choices=[('user', 'user'), ('system', 'system')], max_length=10)),
                ('book_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.bookforuser')),
            ],
            options={
                'verbose_name_plural': 'Book Chat Messages',
                'ordering': ('id',),
            },
        ),
    ]
