# Generated by Django 5.1.6 on 2025-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bookchatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchatmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='bookchatmessage',
            name='simple_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookchatmessage',
            name='slide_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookchatmessage',
            name='speech_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
