# Generated by Django 5.1.6 on 2025-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_classroom_classroomcontent_classroommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher_voice_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
