# Generated by Django 5.1.6 on 2025-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_classroom_teacher_voice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomcontent',
            name='content_is_explained',
            field=models.BooleanField(default=False),
        ),
    ]
