# Generated by Django 5.1.6 on 2025-09-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_classroomcontent_content_is_explained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomcontent',
            name='content',
        ),
        migrations.AddField(
            model_name='classroomcontent',
            name='slides',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
