# Generated by Django 5.1.6 on 2025-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_classroomcontent_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomcontent',
            name='audio_length_sec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classroomcontent',
            name='ssml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
